GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "grey",
    "password": "longlongtimeago",
    "name": "Gandalf the Grey"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "white",
    "password": "thereandbackagain",
    "name": "Gandalf the White"
}
